name: Pipeline-CI
on:
  push:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@2.34.1
        with:
          extensions: ctype, dom, filter, gd, iconv, intl, json, mbstring, pdo, pdo_mysql, xml

      - name: Cache multiple paths
        uses: actions/cache@v4.2.3
        with:
          path: |
            vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: "Composer install"
        run: composer install --no-interaction --no-progress

      # Install Symfony CLI
      - name: Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

      # Check vulnerabilities
      - name: Symfony Check Vulnerabilities
        run: symfony check:security
