name: Pipeline-CI
on:
  push:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@2.34.1
        with:
          extensions: ctype, dom, filter, gd, iconv, intl, json, mbstring, pdo, pdo_mysql, xml
      
      - name: LS
        run: ls
